/* ###################################################################
**     This component module is generated by Processor Expert. Do not modify it.
**     Filename    : iseled1.h
**     Project     : iseled_freemaster_s32k144
**     Processor   : S32K144_100
**     Component   : iseled
**     Version     : Component SDK_S32K1xx_15, Driver 01.00, CPU db: 3.00.000
**     Repository  : SDK_S32K1xx_15
**     Compiler    : GNU C Compiler
**     Date/Time   : 2020-07-22, 21:53, # CodeGen: 75
**     Contents    :
**         digLED_Init_Interface  - digLED_ReturnType digLED_Init_Interface(uint8_t nrOfInterfaces,const...
**         digLED_Init_Strip      - digLED_ReturnType digLED_Init_Strip(const digLED_InitType *...
**         digLED_Set_RGB         - digLED_ReturnType digLED_Set_RGB(uint8_t Red,uint8_t Green,uint8_t...
**         digLED_Test            - digLED_ReturnType digLED_Test(uint8_t TestNr,uint16_t Address,uint8_t stripNr);
**         digLED_Reset           - digLED_ReturnType digLED_Reset(uint8_t stripNr);
**         digLED_Set_Config      - digLED_ReturnType digLED_Set_Config(uint16_t Param,uint16_t Address,uint8_t...
**         digLED_Set_PWM_Red     - digLED_ReturnType digLED_Set_PWM_Red(uint16_t Param,uint16_t Address,uint8_t...
**         digLED_Set_PWM_Green   - digLED_ReturnType digLED_Set_PWM_Green(uint16_t Param,uint16_t...
**         digLED_Set_PWM_Blue    - digLED_ReturnType digLED_Set_PWM_Blue(uint16_t Param,uint16_t Address,uint8_t...
**         digLED_Set_Cur_Green   - digLED_ReturnType digLED_Set_Cur_Green(uint16_t Param,uint16_t...
**         digLED_Set_Cur_Blue    - digLED_ReturnType digLED_Set_Cur_Blue(uint16_t Param,uint16_t Address,uint8_t...
**         digLED_Set_Temp_Offset - digLED_ReturnType digLED_Set_Temp_Offset(uint16_t Param,uint16_t...
**         digLED_Set_Trg_Adc_Cal - digLED_ReturnType digLED_Set_Trg_Adc_Cal(uint8_t Mode,uint16_t...
**         digLED_Set_Bias        - digLED_ReturnType digLED_Set_Bias(uint16_t Param,uint16_t Address,uint8_t...
**         digLED_Set_TC_Base     - digLED_ReturnType digLED_Set_TC_Base(uint16_t Param,uint16_t Address,uint8_t...
**         digLED_Set_Adc_Dac     - digLED_ReturnType digLED_Set_Adc_Dac(uint16_t Param,uint16_t Address,uint8_t...
**         digLED_Set_TC_Lookup   - digLED_ReturnType digLED_Set_TC_Lookup(uint16_t LUT_Adr,uint16_t...
**         digLED_Set_TC_Offset   - digLED_ReturnType digLED_Set_TC_Offset(uint16_t Param,uint16_t...
**         digLED_Read_Temp       - digLED_ReturnType digLED_Read_Temp(digLED_ReadDataResultType *...
**         digLED_Read_Status     - digLED_ReturnType digLED_Read_Status(digLED_ReadDataResultType *...
**         digLED_Read_Diagnostic - digLED_ReturnType digLED_Read_Diagnostic(digLED_ReadDataResultType *...
**         digLED_Read_Param      - digLED_ReturnType digLED_Read_Param(uint8_t...
**         digLED_Set_Dim         - digLED_ReturnType digLED_Set_Dim(uint8_t Red,uint8_t Green,uint8_t...
**         digLED_Define_Mcast    - digLED_ReturnType digLED_Define_Mcast(uint16_t Param,uint16_t Address,uint8_t...
**         digLED_Read_PWM_Red    - digLED_ReturnType digLED_Read_PWM_Red(digLED_ReadDataResultType *...
**         digLED_Read_PWM_Green  - digLED_ReturnType digLED_Read_PWM_Green(digLED_ReadDataResultType *...
**         digLED_Read_PWM_Blue   - digLED_ReturnType digLED_Read_PWM_Blue(digLED_ReadDataResultTypee *...
**         digLED_Ping            - digLED_ReturnType digLED_Ping(digLED_ReadDataResultTypee *...
**         digLED_Send_Cmd_Block  - digLED_ReturnType digLED_Send_Cmd_Block(digLED_SendCmdBlockType...
**         digLED_Set_Timeout     - digLED_ReturnType digLED_Set_Timeout(uint32_t duration, uint8_t stripNr);
**
**     Copyright 1997 - 2015 Freescale Semiconductor, Inc. 
**     Copyright 2016-2017 NXP 
**     All Rights Reserved.
**     
**     THIS SOFTWARE IS PROVIDED BY NXP "AS IS" AND ANY EXPRESSED OR
**     IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES
**     OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED.
**     IN NO EVENT SHALL NXP OR ITS CONTRIBUTORS BE LIABLE FOR ANY DIRECT,
**     INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
**     (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR
**     SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION)
**     HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT,
**     STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING
**     IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF
**     THE POSSIBILITY OF SUCH DAMAGE.
** ###################################################################*/
/*!
** @file iseled1.h
** @version 01.00
*/         
/*!
**  @addtogroup iseled1_module iseled1 module documentation
**  @{
*/         
#ifndef iseled1_H
#define iseled1_H

/* MODULE iseled1.
 *
 * @page misra_violations MISRA-C:2012 violations
 *
 * @section [global]
 * Violates MISRA 2012 Advisory Rule 2.5, Global macro not referenced.
 * The global macro will be used in function call of the module.
 */

/* Include inherited beans */
#include "clockMan1.h"
#include "dmaController1.h"
#include "timing_pal1.h"
#include "Cpu.h"
/*! Device instance number */
#include "iseled1.h"




















			
			
			

			
				

		
		
#define NUMBER_OF_STRIPS_FLEXIO 1
#define NUMBER_OF_STRIPS_LPSPI 0
#define NUMBER_OF_INTERFACES 1

extern void digLED_Callback(digLED_CommEventType state, uint8_t stripNr);
			
			
extern digLED_ConfigType iseled1_InitConfig[NUMBER_OF_INTERFACES];

#endif
/* END iseled1 */
/*!
** @}
*/
/*
** ###################################################################
**
**     This file was created by Processor Expert 10.1 [05.21]
**     for the Freescale S32K series of microcontrollers.
**
** ###################################################################
*/

